/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'EasyCollectionMsg'
 * message type.
 */

public class EasyCollectionMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 24;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 23;

    /** Create a new EasyCollectionMsg of size 24. */
    public EasyCollectionMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new EasyCollectionMsg of the given data_length. */
    public EasyCollectionMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new EasyCollectionMsg with the given data_length
     * and base offset.
     */
    public EasyCollectionMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new EasyCollectionMsg using the given byte array
     * as backing store.
     */
    public EasyCollectionMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new EasyCollectionMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public EasyCollectionMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new EasyCollectionMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public EasyCollectionMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new EasyCollectionMsg embedded in the given message
     * at the given base offset.
     */
    public EasyCollectionMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new EasyCollectionMsg embedded in the given message
     * at the given base offset and length.
     */
    public EasyCollectionMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <EasyCollectionMsg> \n";
      try {
        s += "  [id=0x"+Long.toHexString(get_id())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [count=0x"+Long.toHexString(get_count())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [reading=";
        for (int i = 0; i < 10; i++) {
          s += "0x"+Long.toHexString(getElement_reading(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: id
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'id' is signed (false).
     */
    public static boolean isSigned_id() {
        return false;
    }

    /**
     * Return whether the field 'id' is an array (false).
     */
    public static boolean isArray_id() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'id'
     */
    public static int offset_id() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'id'
     */
    public static int offsetBits_id() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'id'
     */
    public int get_id() {
        return (int)getUIntBEElement(offsetBits_id(), 16);
    }

    /**
     * Set the value of the field 'id'
     */
    public void set_id(int value) {
        setUIntBEElement(offsetBits_id(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'id'
     */
    public static int size_id() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'id'
     */
    public static int sizeBits_id() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: count
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'count' is signed (false).
     */
    public static boolean isSigned_count() {
        return false;
    }

    /**
     * Return whether the field 'count' is an array (false).
     */
    public static boolean isArray_count() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'count'
     */
    public static int offset_count() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'count'
     */
    public static int offsetBits_count() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'count'
     */
    public int get_count() {
        return (int)getUIntBEElement(offsetBits_count(), 16);
    }

    /**
     * Set the value of the field 'count'
     */
    public void set_count(int value) {
        setUIntBEElement(offsetBits_count(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'count'
     */
    public static int size_count() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'count'
     */
    public static int sizeBits_count() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: reading
    //   Field type: int[], unsigned
    //   Offset (bits): 32
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'reading' is signed (false).
     */
    public static boolean isSigned_reading() {
        return false;
    }

    /**
     * Return whether the field 'reading' is an array (true).
     */
    public static boolean isArray_reading() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'reading'
     */
    public static int offset_reading(int index1) {
        int offset = 32;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'reading'
     */
    public static int offsetBits_reading(int index1) {
        int offset = 32;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'reading' as a int[]
     */
    public int[] get_reading() {
        int[] tmp = new int[10];
        for (int index0 = 0; index0 < numElements_reading(0); index0++) {
            tmp[index0] = getElement_reading(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'reading' from the given int[]
     */
    public void set_reading(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_reading(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'reading'
     */
    public int getElement_reading(int index1) {
        return (int)getUIntBEElement(offsetBits_reading(index1), 16);
    }

    /**
     * Set an element of the array 'reading'
     */
    public void setElement_reading(int index1, int value) {
        setUIntBEElement(offsetBits_reading(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'reading'
     */
    public static int totalSize_reading() {
        return (160 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'reading'
     */
    public static int totalSizeBits_reading() {
        return 160;
    }

    /**
     * Return the size, in bytes, of each element of the array 'reading'
     */
    public static int elementSize_reading() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'reading'
     */
    public static int elementSizeBits_reading() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'reading'
     */
    public static int numDimensions_reading() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'reading'
     */
    public static int numElements_reading() {
        return 10;
    }

    /**
     * Return the number of elements in the array 'reading'
     * for the given dimension.
     */
    public static int numElements_reading(int dimension) {
      int array_dims[] = { 10,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
