COMPONENT=EasyCollectionAppC
CFLAGS += -I$(TOSDIR)/lib/net \
                   -I$(TOSDIR)/lib/net/le \
                   -I$(TOSDIR)/lib/net/ctp \
                   -I$(TOSDIR)/lib/net/drip
clean :
	rm EasyCollection.class EasyCollectionMsg.java 
include $(MAKERULES)
